version: '3'
services:
  app:
    tty: true
    stdin_open: true
    build: .
    volumes:
      - .:/var/app
      - /var/app/vendor
    ports:
      - '3000:3000'
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Tokyo
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
